# Generated by Django 3.2.13 on 2022-06-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demanddata',
            old_name='ID1',
            new_name='ID',
        ),
    ]
