# Generated by Django 3.2.13 on 2022-06-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_id1_demanddata_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='demandData',
            new_name='Forecast_Master',
        ),
    ]
