# Generated by Django 3.2.13 on 2022-06-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_forecast_master_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast_master',
            name='forecast_term',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
