# Generated by Django 3.2.13 on 2022-06-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_forecast_master_forecast_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('Block', models.IntegerField(blank=True, null=True)),
                ('Called_At', models.DateTimeField(blank=True, null=True)),
                ('GeoCode', models.CharField(blank=True, max_length=200, null=True)),
                ('cloudCover', models.FloatField(blank=True, null=True)),
                ('dayOfWeek', models.CharField(blank=True, max_length=200, null=True)),
                ('dayOrNight', models.CharField(blank=True, max_length=200, null=True)),
                ('precipChance', models.FloatField(blank=True, null=True)),
                ('precipType', models.CharField(blank=True, max_length=200, null=True)),
                ('pressureMeanSeaLevel', models.FloatField(blank=True, null=True)),
                ('qpf', models.FloatField(blank=True, null=True)),
                ('qpfSnow', models.FloatField(blank=True, null=True)),
                ('relativeHumidity', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('temperatureDewPoint', models.FloatField(blank=True, null=True)),
                ('temperatureFeelsLike', models.FloatField(blank=True, null=True)),
                ('temperatureHeatIndex', models.FloatField(blank=True, null=True)),
                ('temperatureWindChill', models.FloatField(blank=True, null=True)),
                ('uvDescription', models.CharField(blank=True, max_length=200, null=True)),
                ('uvIndex', models.FloatField(blank=True, null=True)),
                ('validTimeLocal', models.DateTimeField(blank=True, null=True)),
                ('visibility', models.FloatField(blank=True, null=True)),
                ('windDirection', models.FloatField(blank=True, null=True)),
                ('windDirectionCardinal', models.CharField(blank=True, max_length=200, null=True)),
                ('windGust', models.FloatField(blank=True, null=True)),
                ('windSpeed', models.FloatField(blank=True, null=True)),
                ('wxPhraseLong', models.CharField(blank=True, max_length=200, null=True)),
                ('wxPhraseShort', models.CharField(blank=True, max_length=200, null=True)),
                ('wxSeverity', models.IntegerField(blank=True, null=True)),
                ('StateCode', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
